set_property IOSTANDARD LVCMOS33 [get_ports {eth0_rxd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {eth0_rxd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {eth0_rxd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {eth0_rxd[0]}]
set_property PACKAGE_PIN R8 [get_ports {eth0_rxd[3]}]
set_property PACKAGE_PIN R7 [get_ports {eth0_rxd[2]}]
set_property PACKAGE_PIN T7 [get_ports {eth0_rxd[1]}]
set_property PACKAGE_PIN N6 [get_ports {eth0_rxd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {eth0_txd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {eth0_txd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {eth0_txd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {eth0_txd[0]}]
set_property PACKAGE_PIN P9 [get_ports {eth0_txd[3]}]
set_property PACKAGE_PIN T9 [get_ports {eth0_txd[2]}]
set_property PACKAGE_PIN T10 [get_ports {eth0_txd[1]}]
set_property PACKAGE_PIN R10 [get_ports {eth0_txd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {eth1_rxd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {eth1_rxd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {eth1_rxd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {eth1_rxd[0]}]
set_property PACKAGE_PIN C9 [get_ports {eth1_rxd[3]}]
set_property PACKAGE_PIN A10 [get_ports {eth1_rxd[2]}]
set_property PACKAGE_PIN B10 [get_ports {eth1_rxd[1]}]
set_property PACKAGE_PIN B9 [get_ports {eth1_rxd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {eth1_txd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {eth1_txd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {eth1_txd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {eth1_txd[0]}]
set_property PACKAGE_PIN A12 [get_ports {eth1_txd[3]}]
set_property PACKAGE_PIN A13 [get_ports {eth1_txd[2]}]
set_property PACKAGE_PIN A14 [get_ports {eth1_txd[1]}]
set_property PACKAGE_PIN B14 [get_ports {eth1_txd[0]}]
set_property PACKAGE_PIN E12 [get_ports clk_25mhz]
set_property IOSTANDARD LVCMOS33 [get_ports clk_25mhz]
set_property IOSTANDARD LVCMOS33 [get_ports eth1_mdc]
set_property PACKAGE_PIN A8 [get_ports eth1_mdc]
set_property PACKAGE_PIN D10 [get_ports eth1_mdio]
set_property IOSTANDARD LVCMOS33 [get_ports eth1_mdio]
set_property PACKAGE_PIN D9 [get_ports eth1_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports eth1_rst_n]
set_property PACKAGE_PIN C11 [get_ports eth1_rx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports eth1_rx_clk]
set_property PACKAGE_PIN A9 [get_ports eth1_rx_ctl]
set_property IOSTANDARD LVCMOS33 [get_ports eth1_rx_ctl]
set_property PACKAGE_PIN B12 [get_ports eth1_tx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports eth1_tx_clk]
set_property PACKAGE_PIN B11 [get_ports eth1_tx_ctl]
set_property IOSTANDARD LVCMOS33 [get_ports eth1_tx_ctl]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN H12 [get_ports {led[3]}]
set_property PACKAGE_PIN H13 [get_ports {led[2]}]
set_property PACKAGE_PIN J16 [get_ports {led[1]}]
set_property PACKAGE_PIN J15 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports eth0_mdc]
set_property PACKAGE_PIN R5 [get_ports eth0_mdc]
set_property PACKAGE_PIN T5 [get_ports eth0_mdio]
set_property IOSTANDARD LVCMOS33 [get_ports eth0_mdio]
set_property PACKAGE_PIN R6 [get_ports eth0_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports eth0_rst_n]
set_property PACKAGE_PIN N11 [get_ports eth0_rx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports eth0_rx_clk]
set_property PACKAGE_PIN P6 [get_ports eth0_rx_ctl]
set_property IOSTANDARD LVCMOS33 [get_ports eth0_rx_ctl]
set_property PACKAGE_PIN P8 [get_ports eth0_tx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports eth0_tx_clk]
set_property PACKAGE_PIN T8 [get_ports eth0_tx_ctl]
set_property IOSTANDARD LVCMOS33 [get_ports eth0_tx_ctl]

create_clock -period 40.000 -name clk_25mhz -waveform {0.000 20.000} [get_ports clk_25mhz]
create_clock -period 8.000 -name eth0_rx_clk -waveform {0.000 4.000} [get_ports eth0_rx_clk]
create_clock -period 8.000 -name eth1_rx_clk -waveform {0.000 4.000} [get_ports eth1_rx_clk]
create_generated_clock -name clk_system -source [get_pins clkgen/pll/mmcm/CLKIN1] -master_clock clk_25mhz [get_pins clkgen/pll/mmcm/CLKOUT0]
create_generated_clock -name clk_125mhz -source [get_pins clkgen/pll/mmcm/CLKIN1] -master_clock clk_25mhz [get_pins clkgen/pll/mmcm/CLKOUT1]
create_generated_clock -name clk_250mhz -source [get_pins clkgen/pll/mmcm/CLKIN1] -master_clock clk_25mhz [get_pins clkgen/pll/mmcm/CLKOUT2]
set_clock_groups -asynchronous -group [get_clocks eth0_rx_clk] -group [get_clocks clk_125mhz]
set_clock_groups -asynchronous -group [get_clocks eth1_rx_clk] -group [get_clocks clk_125mhz]
set_clock_groups -asynchronous -group [get_clocks clk_125mhz] -group [get_clocks eth0_rx_clk]
set_clock_groups -asynchronous -group [get_clocks clk_125mhz] -group [get_clocks eth1_rx_clk]
